import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import yukiiko from "../public/assets/yukiikoart.jpg";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Yuukiiko Sora</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className="h-screen w-auto flex flex-col items-center justify-center bg-rose-200 pt-20 px-7">
        <div className="font-fredoka text-slate-50 text-center mb-7">
          <div>
            <Image
              className="rounded-full"
              src={yukiiko}
              alt="Yukiiko Sora"
              width={270}
              height={270}
            />
          </div>
          <p className="text-3xl tracking-widest">yukiiko sora</p>
          <p className="text-sm">Illustrator, Character art & Design</p>
        </div>
        <div className="text-justify text-slate-50 font-semibold">
          <p className="mb-2">
            Hi I&apos;m yukiko, please call me yuki. I draw fan art and original
            illustrations.
          </p>
          <p>
            ゆきいこと呼んでいいです。ファンアートとオリジナルなイラストを描いています。
          </p>
        </div>
      </main>
    </div>
  );
}
